### ISSUE TITLE
Not works in expo!

### ISSUE THREAD

**Issue by EduGomes18** [tokkozhin/react-native-neomorph-shadows#14] opened 2020-05-01 15:28 UTC
I try to use with expo and it doesnt work, i think it`s because they eject the ART lib, i get this error :Error while updating property 'stroke' in shadow node of type: ARTShape

**Comment by tokkozhin** [comment] 2020-05-01 19:00
Duplicate of #10

**Closed as completed by tokkozhin** 2020-05-01 19:00 UTC
