### ISSUE TITLE
couldn't start project

### ISSUE THREAD

**Issue by ulantiger** [tokkozhin/react-native-neomorph-shadows#16] opened 2020-05-06 09:49 UTC
Hello there,
I have spent many hours to build a project with your components on Windows for Android. I couldn't start the project, nothing showed up or had constant problems with @react-native-community/art library.  I have tried to run on an emulator and physical device. So failed on both.
![Android test 2020-05-06 at 11 47 48](https://user-images.githubusercontent.com/25429876/81163780-8ef90080-8f8f-11ea-8ba2-012e95b682ff.jpeg)

**Comment by shafayeatsumit** [comment] 2020-05-06 11:01
I am having the same issue.

**Comment by tokkozhin** [comment] 2020-05-06 14:38
Duplicate of #10

**Closed as completed by tokkozhin** 2020-05-06 14:38 UTC
