### ISSUE TITLE
Invariant Violation: View config not found for name ARTShape.

### ISSUE THREAD

**Issue by IceTeddy** [tokkozhin/react-native-neomorph-shadows#19] opened 2020-05-13 09:18 UTC
![Simulator Screen Shot - iPhone 11 - 2020-05-13 at 17 17 23](https://user-images.githubusercontent.com/1934749/81794825-f25dd200-953d-11ea-8d77-7f8ad2c6b97e.png)

**Comment by tokkozhin** [comment] 2020-05-13 10:25
Hi, If you use expo, see 
Duplicate of #10

**Closed as completed** 2020-05-15 21:35 UTC
